/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Jan 15 18:44:33 2015. */

#include "car_to_server.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const float CarMessage_accelX_default = 0;
const float CarMessage_accelY_default = 0;
const float CarMessage_accelZ_default = 0;
const FireType CarMessage_fireType_default = FireType_NO_FIRE;
const bool CarMessage_isFireLive_default = false;
const int32_t CarMessage_carId_default = -1;
const bool CarMessage_isActiveStatus_default = false;
const bool CarMessage_isFireLiveStatus_default = false;
const CarMessage_TeamType CarMessage_teamStatus_default = CarMessage_TeamType_INVALID_TEAM;
const uint32_t CarMessage_ledColour_default = 0u;


const pb_field_t CarMessage_fields[12] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, CarMessage, type, type, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, CarMessage, accelX, type, &CarMessage_accelX_default),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, CarMessage, accelY, accelX, &CarMessage_accelY_default),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, CarMessage, accelZ, accelY, &CarMessage_accelZ_default),
    PB_FIELD(  5, ENUM    , OPTIONAL, STATIC  , OTHER, CarMessage, fireType, accelZ, &CarMessage_fireType_default),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, CarMessage, isFireLive, fireType, &CarMessage_isFireLive_default),
    PB_FIELD(  7, SINT32  , OPTIONAL, STATIC  , OTHER, CarMessage, carId, isFireLive, &CarMessage_carId_default),
    PB_FIELD(  8, BOOL    , OPTIONAL, STATIC  , OTHER, CarMessage, isActiveStatus, carId, &CarMessage_isActiveStatus_default),
    PB_FIELD(  9, BOOL    , OPTIONAL, STATIC  , OTHER, CarMessage, isFireLiveStatus, isActiveStatus, &CarMessage_isFireLiveStatus_default),
    PB_FIELD( 10, ENUM    , OPTIONAL, STATIC  , OTHER, CarMessage, teamStatus, isFireLiveStatus, &CarMessage_teamStatus_default),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, CarMessage, ledColour, teamStatus, &CarMessage_ledColour_default),
    PB_LAST_FIELD
};


