/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Jan 15 18:45:36 2015. */

#ifndef PB_COMMON_PB_H_INCLUDED
#define PB_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _FireType {
    FireType_NO_FIRE = 0,
    FireType_SMALL_BURST = 1,
    FireType_MEDIUM_BURST = 2,
    FireType_LARGE_BURST = 3
} FireType;

/* Struct definitions */
/* Default values for struct fields */

/* Initializer values for message structs */

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
