/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Jan 15 18:45:36 2015. */

#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif




