/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Jan 15 18:48:57 2015. */

#ifndef PB_SERVER_TO_CAR_PB_H_INCLUDED
#define PB_SERVER_TO_CAR_PB_H_INCLUDED
#include <pb.h>

#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ServerMessage_MessageType {
    ServerMessage_MessageType_STATUS_QUERY = 0,
    ServerMessage_MessageType_SET_LED_COLOUR_CMD = 1,
    ServerMessage_MessageType_SET_IS_ACTIVE_CMD = 2,
    ServerMessage_MessageType_SHOOT_FIRE_CMD = 3,
    ServerMessage_MessageType_COLLISION_INFO = 4
} ServerMessage_MessageType;

/* Struct definitions */
typedef struct _ServerMessage {
    ServerMessage_MessageType type;
    bool has_ledColour;
    uint32_t ledColour;
    bool has_isActive;
    bool isActive;
    bool has_fireType;
    FireType fireType;
    bool has_rewardCarId;
    int32_t rewardCarId;
    bool has_punishCarId;
    int32_t punishCarId;
    bool has_isFriendlyFire;
    bool isFriendlyFire;
} ServerMessage;

/* Default values for struct fields */
extern const uint32_t ServerMessage_ledColour_default;
extern const bool ServerMessage_isActive_default;
extern const FireType ServerMessage_fireType_default;
extern const int32_t ServerMessage_rewardCarId_default;
extern const int32_t ServerMessage_punishCarId_default;
extern const bool ServerMessage_isFriendlyFire_default;

/* Initializer values for message structs */
#define ServerMessage_init_default               {(ServerMessage_MessageType)0, false, 0u, false, false, false, FireType_NO_FIRE, false, -1, false, -1, false, false}
#define ServerMessage_init_zero                  {(ServerMessage_MessageType)0, false, 0, false, 0, false, (FireType)0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ServerMessage_type_tag                   1
#define ServerMessage_ledColour_tag              2
#define ServerMessage_isActive_tag               3
#define ServerMessage_fireType_tag               4
#define ServerMessage_rewardCarId_tag            5
#define ServerMessage_punishCarId_tag            6
#define ServerMessage_isFriendlyFire_tag         7

/* Struct field encoding specification for nanopb */
extern const pb_field_t ServerMessage_fields[8];

/* Maximum encoded size of messages (where known) */
#define ServerMessage_size                       34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
