/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Jan 15 18:48:57 2015. */

#include "server_to_car.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t ServerMessage_ledColour_default = 0u;
const bool ServerMessage_isActive_default = false;
const FireType ServerMessage_fireType_default = FireType_NO_FIRE;
const int32_t ServerMessage_rewardCarId_default = -1;
const int32_t ServerMessage_punishCarId_default = -1;
const bool ServerMessage_isFriendlyFire_default = false;


const pb_field_t ServerMessage_fields[8] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, ServerMessage, type, type, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ServerMessage, ledColour, type, &ServerMessage_ledColour_default),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ServerMessage, isActive, ledColour, &ServerMessage_isActive_default),
    PB_FIELD(  4, ENUM    , OPTIONAL, STATIC  , OTHER, ServerMessage, fireType, isActive, &ServerMessage_fireType_default),
    PB_FIELD(  5, SINT32  , OPTIONAL, STATIC  , OTHER, ServerMessage, rewardCarId, fireType, &ServerMessage_rewardCarId_default),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, ServerMessage, punishCarId, rewardCarId, &ServerMessage_punishCarId_default),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, ServerMessage, isFriendlyFire, punishCarId, &ServerMessage_isFriendlyFire_default),
    PB_LAST_FIELD
};


